### ISSUE TITLE
Please, re-render

### ISSUE THREAD

**Issue by horta** [conda-forge/h5py-feedstock#17]
In order to build numpy 1.12.

**Comment by jakirkham** [comment]
Please submit a PR. Should be easy to do.

ref: https://github.com/conda-forge/conda-smithy/blob/master/README.md#re-rendering-an-existing-feedstock

**Comment by jakirkham** [comment]
Also please see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/313 ).

**Comment by horta** [comment]
I see. So we have to wait for h5py to be able to be built against numpy, right?

**Comment by jakirkham** [comment]
Please just submit a re-rendering PR if you want it re-rendered. Will happily merge it.
