### ISSUE TITLE
Using h5py from Matlab

### ISSUE THREAD

**Issue by jonc125** [conda-forge/h5py-feedstock#22]
This is a bit of a bizarre use case, I know!

I'm working with a neuroscience library (https://github.com/NeurodataWithoutBorders/api-python) that provides a Matlab interface via a bridge to their Python API, using Matlab's support for accessing Python modules. This library uses h5py to work with HDF5 files. The issue is that Matlab bundles its own version of HDF5 (1.8.12 as of Matlab 2016b) and Strange Things can happen if h5py is using a different HDF5 library.

Unfortunately 1.8.12 is one of the HDF5 versions that isn't available in the default conda channel, nor is it available here. Do you have any advice on the best way to provide non-techy users (some of them on Windows, some on Mac OS) a conda-installable HDF5 1.8.12 and h5py to match?

**Comment by jakirkham** [comment]
Hi @jonc125, thanks for the issue. Am familiar with NWB.

> Strange Things can happen if h5py is using a different HDF5 library.

Could you help me understand what this means? Expecting an important piece of information here is what OS you are using. Also maybe a simple example of your workflow. Finally would be good to know if there is a traceback you are seeing.

**Comment by jonc125** [comment]
One issue is that I have to use `setenv('HDF5_DISABLE_VERSION_CHECK', '1')` to prevent HDF5 aborting; that's fairly easy to do however.

The larger issue is that I'd like to use Matlab's HDF5 routines to read datasets, rather than going via Python, but the Python API makes writing files and enumerating contents much easier. When the HDF5 versions match I can do
```
mat_file_id = double(nwb_file.fg_file.file_pointer.fid.id)
```
and pass this id to Matlab's routines (e.g. `H5D.open`). If the versions don't match, I get
```
>> H5F.reopen(mat_file_id)
Error using hdf5lib2
The HDF5 library encountered an error and produced the following stack trace information:

    H5Freopen    not a file

Error in H5F.reopen (line 10)
raw_file_id = H5ML.hdf5lib2('H5Freopen', file_id);
```

The odd thing is that this _used_ to work even with h5py 2.7 and HDF5 1.8.17 three months ago when I started working with NWB, but some change to my anaconda env since (I've had to install a few other packages including pandas for related work) has made it much more picky.

**Comment by jonc125** [comment]
Should add I'm developing on Mac OS, with Python 2.7 in an Anaconda env. My automated test system (Linux) has HDF5 1.8.12 and works as expected.

**Comment by jakirkham** [comment]
Sorry I'm still not understanding something about your workflow. Given MATLAB has it's own function for opening, reading, and writing to HDF5 files, why not just use these instead of sharing the file ID between processes?

**Comment by jonc125** [comment]
It's not sharing an ID between processes, as I understand it - the Python code is running within the Matlab process. The issue with opening the file separately in Matlab (which I am currently doing as a workaround) is that depending on OS having a file open multiple times is problematic, especially if you're reading in one case and writing in the other. At present I'm just reading in both, so think I can get away with the workaround (although not yet tested on Windows), but will need read/write support in the future, when adding the results of processing steps - I want to use the NWB API to create the groups so the file validates OK, but Matlab's API to add the data for speed.

**Comment by tacaswell** [comment]
The safest thing here is to build your own packages (of hdf5, h5py, and likely pytables) and put them on your own channel (which of I suspect is going to depend on the MATLAB version you have).

It might be simpler to just write a MATLAB based API for NWB :disappointed: 

When you are passing the ID between the MATLAB and python sides you are putting a hole in both of their garbage collection mechanisms, I am no longer clear who owns the underlying c pointer and am concerned that one side or the other will de-allocate it and the other side will segfault (there could be one more layer of indirection here so this is OK).

**Comment by zxdawn** [comment]
@jonc125 How did you deal with this issue finally?

**Comment by jonc125** [comment]
I didn't really. As a temporary workaround I built my own packages as outlined above, which got things partially working, but now there's a pure Matlab API for NWB which we'll be switching to.

**Comment by zxdawn** [comment]
@jonc125 Thank you. I built my own h5py=2.7.1 based on hdf5=1.8.12 and it works fine now.
