### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/h5py-feedstock#37]
Issue:

Python 3.7 not in build matrix. This is the last dependency I need to get a working py3.7 stack. Is anything blocking python3.7 builds? 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
> Python 3.7 not in build matrix. This is the last dependency I need to get a working py3.7 stack. Is anything blocking python3.7 builds?

Officially the py37 builds will be handle by the bot in topological order.
If you cannot wait you can try to do that yourself by adding `max_py_ver: '37'` in the `conda-forge.yml` and re-rendering, but you may dive into a dependency hell and find yourself building tons of dependencies :smile:

**Comment by kmuehlbauer** [comment]
@ocefpaf OK, I somehow thought the bot is doing the new compilers, got this mixed-up. So I'll wait for the bot. :grinning:

**Comment by ocefpaf** [comment]
> @ocefpaf OK, I somehow thought the bot is doing the new compilers, got this mixed-up. So I'll wait for the bot. :grinning:

That too. And the new R version. We decided to do the 3 big migrations in one go to avoid multiple re-builds.
