### ISSUE TITLE
h5py parallel build

### ISSUE THREAD

**Issue by carterbox** [conda-forge/h5py-feedstock#44]
The conda-forge hdf5 now offers a parallel build (conda-forge/hdf5-feedstock#90). I'd really like to see this channel offer a parallel h5py build as well. What can I do to help get this going?

**Comment by jakirkham** [comment]
cc @minrk

**Comment by carterbox** [comment]
For posterity, the most graceful way to install the h5py mpi build is
```bash
conda install "h5py>=2.9=mpi*"  # 2.9 is the first version built with mpi on this channel
```
because the h5py build recipe does not track features. This was intentional; the h5py mpi build will never be installed automatically even if mpi is already installed.

**Comment by wesbz** [comment]
Thanks @carterbox, this worked! Would it be possible to update the doc as the instructions from the doc do not work.

**Comment by jakirkham** [comment]
Which docs are you referring too?

**Comment by wesbz** [comment]
I tried to follow [this documentation](https://docs.h5py.org/en/stable/build.html). It did not work...

**Comment by jakirkham** [comment]
That looks like h5py's documentation, right? There's not much we can do here (in conda-forge) to address that. Would suggest [raising an issue on the h5py repo]( https://github.com/h5py/h5py/issues ). They might appreciate a bit more context as to exactly what you tried,  what happened, what was needed to fix it, and maybe even suggestions on how the docs can be improved.
