### ISSUE TITLE
Update to hdf5 1.10.5

### ISSUE THREAD

**Issue by ChristopherHogan** [conda-forge/h5py-feedstock#52]
The bot just went around trying to get everything on hdf5 1.10.5, but if a project has a build dependency on hdf5 and a run dependency on h5py, then hdf5 must be pinned to 1.10.4 because h5py is pinned to 1.10.4.

**Comment by ocefpaf** [comment]
See #51

**Comment by ChristopherHogan** [comment]
Thanks. So in the meantime I should pin all my recipes that have h5py as a run dependency to hdf5 1.10.4?

**Comment by ocefpaf** [comment]
No need. Just let the bot handle it. If a PR is issued to `hdf5 1.10.5` and it fails b/c of the lack of `h5py` you can just close it and wait for the next bot cycle.
