### ISSUE TITLE
NumPy matrix was not present in release 0

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/h5py-feedstock#6]
See https://github.com/conda-forge/h5py-feedstock/commit/88995874fa128d3e4d1327b74a49960896887122#diff-e178b687b10a71a3348107ae3154e44cR35

I am removing those binaries from the channel as they conflict with the default channel and they are broken.

**Comment by jakirkham** [comment]
Thanks @ocefpaf.

**Comment by ocefpaf** [comment]
I realized this b/c I need to pin [`h5netcdf`](https://github.com/conda-forge/h5netcdf-feedstock/pull/1/files) to the default channel `h5py` to conflicts with `libnetcdf`.

**Comment by jakirkham** [comment]
Sorry they are causing you problems. This was a terrible mistake on my part. Though I did try to fix it as soon as I realized what I had done, but I didn't figure out how to re-render at the time.

**Comment by ocefpaf** [comment]
Oh don't worry. The problem here is not a big deal. The real problem is the mismatch we have between `libnetcdf` from defaults and our own `hdf5`.
