### ISSUE TITLE
h5py for hdf5=1.12.0

### ISSUE THREAD

**Issue by satra** [conda-forge/h5py-feedstock#91]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

trying to install h5py with hdf5=1.12.0 and it complains about a conflict. i don't exactly know how the build-mechanism works, but would it be possible to enable builds for both 1.10.6 (currently seems to build against this) and 1.12.0 ?

**Comment by satra** [comment]
@jakirkham - pinging here in case you have an easy solution.

**Comment by satra** [comment]
@jakirkham - any thoughts on this issue?

**Comment by ajelenak** [comment]
You can try removing h5py from the conda environment and then re-installing it with that environment's pip command. That h5py will come with the HDF5-1.12.0 library.

**Comment by satra** [comment]
@ajelenak - that does not solve the conda issue though, and also requires that the environment be setup to actually compile hdf5.  the conda forge feedstock for hdf5 is compiled with a few flags (e.g., ROS3 support) that makes this an ideal install mechanism for h5py for users who want to use ROS3 and/or MPIO.

**Comment by ajelenak** [comment]
No HDF5 compilation needed with `pip install h5py`. ROS3VFD is available this way, too, but not MPI.

**Comment by satra** [comment]
> No HDF5 compilation needed with pip install h5py. ROS3VFD is available this way, too ...

thanks @ajelenak - did not know this has changed.

**Comment by satra** [comment]
@ajelenak - i'll try out your suggestion, but will leave this issue open, since it relates to the conda-forge install. thanks very much for the pointer.

**Comment by minrk** [comment]
This was fixed by #98 (`conda create --dry-run -n test h5py hdf5=1.12`)
