### ISSUE TITLE
pyreadline dependency will break on Python 3.10

### ISSUE THREAD

**Issue by bilderbuchi** [conda-forge/h5py-feedstock#93]
Just a heads-up on an approaching packaging problem:
Since #29 you have pyreadline as a dependency (btw this is undocumented in [setup.py](https://github.com/h5py/h5py/blob/master/setup.py) which delayed identifying this issue).
[pyreadline](https://github.com/pyreadline/pyreadline) is unmaintained, last commit 2015, and has since been [abandoned by IPython](https://github.com/pyreadline/pyreadline/pull/68#issuecomment-748396037).

Using pyreadline currently (e.g. py3.9) emits a [deprecation warning](https://github.com/pyreadline/pyreadline/issues/65). This warning will turn into a hard error in Python 3.10, and it does not look like this will be fixed in pyreadline.
```
pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of 
from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

Pyreadline was added here for some functionality related to IPython completion (https://github.com/h5py/h5py/issues/971). Considering Ipython has moved away from this some time ago, probably this code section should be reviewed/updated within h5py proper.

**Comment by bilderbuchi** [comment]
@conda-forge/h5py - is there something missing that you need in this bug report?

**Comment by tacaswell** [comment]
I believe this is already handled here: https://github.com/conda-forge/h5py-feedstock/pull/101 and upstream: https://github.com/h5py/h5py/pull/1964

**Comment by ocefpaf** [comment]
Closing this. Please reopen if you believe it is not fixed as expected.

**Comment by bilderbuchi** [comment]
I just confirmed that the issue is fixed now. Thank you!
