### ISSUE TITLE
Require at least HDF5-1.10.7?

### ISSUE THREAD

**Issue by ajelenak** [conda-forge/h5py-feedstock#96]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Would it be possible to upgrade HDF5 library requirement to at least v1.10.7? This version contains an important fix for `h5py.h5ds.is_scale()` per the release [notes](https://www.hdfgroup.org/2020/09/release-of-hdf5-1-10-7-newsletter-175/):

> The High Level H5DSis_scale function was fixed to correctly handle CLASS and DIMENSION_SCALE attributes that were not written according to the Dimension Scales Specification.

There is also #91 that would fix this issue.

**Comment by ocefpaf** [comment]
Done in #98
